(function(){
  'use strict';
  const B=window.ClayBridge,G=window.ClayGeometry;if(!B||!G)return;
  const root=B.root,field=root.querySelector('.sculpt-field');if(!field)return;
  B.original(false);
  const R=window.ClayRelations(B,G,field);
  const shell=document.createElement('div');shell.className='clay-shell';shell.dataset.clayUi='';
  shell.innerHTML=`<header class="clay-top"><div><span class="clay-brand">Clay Studio<small>Sculpting lab · 0.3</small></span><span class="clay-chip">SHAPE IT BY HAND</span></div><div><button class="original-tools" data-action="original">Layout tools</button><button data-action="phone" aria-pressed="false">Phone</button><button class="site-toggle" data-action="preview" aria-pressed="false">View site</button><button class="clay-export" data-action="export">Export</button></div></header>
  <div class="clay-bottom"><div class="clay-selection" hidden><span></span><button data-tool="peel" aria-pressed="false">Peel a piece</button><button data-action="ungroup">Ungroup</button></div><div class="clay-hint" role="status" aria-live="polite"></div><div class="clay-tools" role="toolbar" aria-label="Sculpting tools">
  <button class="tool" data-tool="hand" aria-pressed="true">Grab</button><button class="tool" data-tool="group" aria-pressed="false">Group</button><button class="tool" data-tool="push" aria-pressed="false">Push</button><button class="tool" data-tool="grow" aria-pressed="false">Grow</button><button class="tool" data-tool="flow" aria-pressed="false">Flow</button><button class="tool" data-tool="smooth" aria-pressed="false">Tidy</button><button class="tool" data-tool="paint" aria-pressed="false">Paint</button><button class="tool" data-tool="pin" aria-pressed="false">Pin</button>
  <span class="separator"></span><label class="clay-options">Brush <input type="range" aria-label="Brush size" min="50" max="380" value="160"><output>160</output></label><input class="clay-color" type="color" aria-label="Paint color" value="#adddc5" hidden>
  <button data-action="magnets" aria-pressed="true" title="Attach small text or a button near a card or image">Magnets</button><button data-action="room" aria-pressed="true" title="Move neighbors aside while sculpting">Make room</button><span class="separator"></span><button data-action="undo" disabled>Undo</button><button data-action="redo" disabled>Redo</button><button data-action="add" aria-expanded="false">Add +</button></div><div class="clay-status">Your edits stay in this browser. Export a page to keep a portable copy.</div>
  <div class="clay-more" hidden><button data-add="text">Add text</button><button data-add="card">Add card</button><button data-add="button">Add button</button><button data-add="image">Add image</button><button data-action="replace" hidden>Replace image</button><button data-action="space">More canvas</button><button data-action="edit">Edit selected text</button></div></div>
  <button class="clay-handle" aria-label="Resize selected piece" title="Drag to resize" hidden></button><canvas class="clay-brush" aria-hidden="true"></canvas><input type="file" class="clay-file" accept="image/*" hidden>
  <dialog class="clay-dialog" aria-label="Export page"><div class="row"><h2>Take your page with you.</h2><button data-action="close-export">Close</button></div><p>Real HTML and CSS. The exported page works without the editor.</p><div class="tabs" role="tablist" aria-label="Export format"><button role="tab" aria-selected="true" data-format="html">Page HTML</button><button role="tab" aria-selected="false" data-format="css">CSS</button><button role="tab" aria-selected="false" data-format="agent">For an agent</button></div><textarea aria-label="Exported source" readonly spellcheck="false"></textarea><div class="actions"><button class="primary" data-action="download">Save HTML file</button><button data-action="copy">Copy current view</button></div><div class="clay-export-state" role="status" aria-live="polite"></div></dialog>`;
  document.body.appendChild(shell);
  const q=s=>shell.querySelector(s),qa=s=>[...shell.querySelectorAll(s)];
  const hint=q('.clay-hint'),canvas=q('canvas'),ctx=canvas.getContext('2d'),handle=q('.clay-handle'),dialog=q('dialog');
  const tips={group:'Drag a box or draw a loop around pieces to stick them together. Pinned pieces stay out.',peel:'Pull a piece 56 pixels out of its group to release it. Escape cancels.',hand:'Grab any piece. Pull its corner to resize. Double-click words to edit.',push:'Brush across the page to push pieces. Pinned pieces stay put.',grow:'Brush upward to grow. Brush downward to shrink. Text stays readable.',flow:'Draw a long path across the canvas. Unpinned cards will follow your stroke.',smooth:'Tidy gently closes oversized gaps and evens nearby rows. Your groups stay together.',paint:'Choose a color, then brush it onto pieces.',pin:'Click a piece to pin it. Click again to let it move.'};
  let tool='hand',radius=160,makeRoom=true,magnets=true,selected=null,gesture=null,lastPoint=null,phone=false,live=false,original=false,format='html',exportHTML='',exportURL='',exportSaving=false;
  let seenError=false,hoveringField=false,wasNarrow=false,fileFor=null;
  function say(text){hint.textContent=text;}
  function items(){return [...field.querySelectorAll(':scope > [data-sculpt-item]')];}
  function bounds(){return {w:field.clientWidth,h:field.clientHeight};}
  function point(e){const r=field.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};}
  function model(){B.stopMotion();const r=field.getBoundingClientRect();return items().map(el=>{
    const box=el.getBoundingClientRect(),style=getComputedStyle(el),kind=el.dataset.kind,font=parseFloat(style.fontSize);
    const content=el.lastElementChild,needed=content?content.getBoundingClientRect().bottom-box.top+parseFloat(style.paddingBottom)+2:30;
    const minW=kind==='group'?R.minimum(el).w:kind==='image'?100:kind==='block'?Math.min(box.width,360):kind==='card'?200:font>34?240:el.classList.contains('eyebrow')?200:140;
    return {id:el.id,el,x:box.left-r.left,y:box.top-r.top,w:box.width,h:box.height,font,pin:style.getPropertyValue('--clay-pin').trim()==='1',minW:Math.min(minW,field.clientWidth),minH:kind==='group'?R.minimum(el).h:(kind==='card'||kind==='block')?needed:30,minFont:font<14?font:14,kind};});}
  function select(el){selected=el;field.querySelectorAll('[data-sculpt-item]').forEach(e=>e.toggleAttribute('data-sculpt-selected',e===el));refresh();}
  function refresh(){const isNarrow=root.clientWidth<=767;qa('[data-tool],[data-action=room],[data-action=magnets],[data-action=add]').forEach(b=>b.disabled=phone||isNarrow);if(isNarrow&&!phone&&!wasNarrow)say('This window shows the phone layout. Widen it to sculpt.');else if(!isNarrow&&wasNarrow&&!phone)say(tips[tool]);wasNarrow=isNarrow;const c=B.counts();q('[data-action=undo]').disabled=!c.undo;q('[data-action=redo]').disabled=!c.redo;
    q('[data-action=replace]').hidden=!imageOf(selected);
    items().forEach(e=>e.toggleAttribute('data-sculpt-locked',getComputedStyle(e).getPropertyValue('--clay-pin').trim()==='1'));
    if(selected&&!selected.isConnected)selected=null;else if(selected)selected=R.unit(selected);field.querySelectorAll('[data-sculpt-item]').forEach(e=>e.toggleAttribute('data-sculpt-selected',e===selected));q('.clay-selection').hidden=!selected||!R.isGroup(selected)||phone||live||original;q('.clay-selection span').textContent=selected&&R.isGroup(selected)?R.members(selected).length+' pieces · move and stretch together':'';handle.hidden=!selected||phone||isNarrow||live||original||tool!=='hand';if(!handle.hidden){const r=selected.getBoundingClientRect();handle.style.left=r.right+'px';handle.style.top=r.bottom+'px';}
  }
  function mobileRules(el){return {el,bp:'mobile',defaults:true,css:{position:'relative',left:'auto',top:'auto',width:'100%','max-width':'100%',height:'auto','min-height':'0',margin:'0',transform:'none',rotate:'none','font-size':el.classList.contains('headline')?'42px':el.dataset.kind==='text'?(el.classList.contains('eyebrow')||el.classList.contains('little')?'13px':'18px'):null}};}
  // A real second layout, stored and exported with the same page. Desktop art direction remains free.
  B.write([{el:field,bp:'mobile',defaults:true,css:{height:'auto',display:'grid',gap:'24px',padding:'30px 24px'}}].concat(items().map(mobileRules)));
  // Only what a gesture actually moved or resized is written, so every other piece keeps its exact values. A piece that
  // moved earlier in the same gesture keeps being written, even if it has come back to where it started.
  function apply(list,label,resize=false,from=null,seen=null){const b=bounds(),near=(a,c)=>Math.abs(a-c)<.5;
    B.write(list.flatMap(i=>{const s=from&&from.find(o=>o.el===i.el);
      let pos=!s||!near(i.x,s.x)||!near(i.y,s.y),size=resize&&!i.pin&&(!s||!near(i.w,s.w)||!near(i.h,s.h)||Math.abs(i.font-s.font)>.05);
      if(seen){if(pos)seen.pos.add(i.el);if(size)seen.size.add(i.el);pos=seen.pos.has(i.el);size=resize&&!i.pin&&seen.size.has(i.el);}
      if(!pos&&!size)return [];const css={};if(pos){css.left=(i.x/b.w*100).toFixed(4)+'%';css.top=i.y.toFixed(2)+'px';}
      if(size){css.width=(i.w/b.w*100).toFixed(4)+'%';if(i.kind==='text')css['font-size']=i.font.toFixed(2)+'px';else if(i.el.tagName==='IMG'||i.kind==='group')css.height=i.h.toFixed(2)+'px';else css['min-height']=i.h.toFixed(2)+'px';}
      return [{el:i.el,css}];}),label);refresh();}
  // Make room clears space for what is moving; pairs that were already crowded before the gesture are left as they were.
  function settle(list,held,crowded=gesture&&gesture.crowded){if(!makeRoom)return {items:list,unresolved:0};return G.separate(list,bounds(),held,undefined,crowded);}
  function setTool(t){if(gesture)finish(false);tool=t;qa('[data-tool]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tool===t)));q('.clay-color').hidden=t!=='paint';say(tips[t]);refresh();draw();}
  function active(){return !phone&&root.clientWidth>767&&!live&&!original&&!dialog.open;}
  function selectedBy(e){return e.target.closest&&R.unit(e.target.closest('[data-sculpt-item]'));}
  function start(e,resize=false){if(!active()||e.button!==0||e.target.isContentEditable)return;let el=resize?selected:selectedBy(e);const p=point(e);lastPoint=p;const peel=(tool==='peel'||e.altKey)&&!resize;if(peel){const hit=e.target.closest('[data-sculpt-item]');if(!hit||!R.isGroup(hit.parentElement)){say('Start on a piece inside a group.');return;}el=hit;if(getComputedStyle(R.unit(el)).getPropertyValue('--clay-pin').trim()==='1'){say('Unpin this group before peeling a piece out.');return;}}
    if(tool==='pin'&&!resize){if(!el){say('Click a piece to pin it.');return;}const before=B.begin(),pin=getComputedStyle(el).getPropertyValue('--clay-pin').trim()!=='1';B.write([{el,css:{'--clay-pin':pin?'1':'0'}}],pin?'Pinned this piece.':'Unpinned this piece.');B.commit(before,pin?'Pinned a piece.':'Unpinned a piece.');select(el);say(pin?'Pinned. Brushes and neighbors will leave this piece in place.':'Unpinned. This piece can move again.');return;}
    if((tool==='hand'||resize||tool==='peel')&&!el){select(null);return;}
    if(el&&(tool==='hand'||resize)&&getComputedStyle(el).getPropertyValue('--clay-pin').trim()==='1'){select(el);say('This piece is pinned. Use Pin to release it first.');return;}
    e.preventDefault();e.stopPropagation();q('.clay-more').hidden=true;q('[data-action=add]').setAttribute('aria-expanded','false');
    const before=B.begin(),all=model();gesture={id:e.pointerId,start:p,prev:p,before,seen:{pos:new Set(),size:new Set()},crowded:G.crowded(all),all:all.map(i=>({...i})),now:all.map(i=>({...i})),path:[p],moved:false,resize,el,painted:new Set(),lastOutcome:0,guides:[],flowValid:false,peel,peeled:false,peelBox:peel?R.rect(el):null,magnet:null,groupSizes:new Map(all.filter(i=>i.kind==='group').map(i=>[i.id,R.resizeState(i.el)]))};
    if(el&&tool==='hand')select(el);if(tool==='flow'){gesture.flowIds=all.filter(i=>(i.kind==='card'||i.kind==='group')&&!i.pin).map(i=>i.id);say('Drawing a path for '+gesture.flowIds.length+' cards. Keep drawing until they settle.');}
    try{field.setPointerCapture(e.pointerId);}catch(err){}if(tool==='paint')paint(p);draw();
  }
  function paint(p){const targets=gesture.now.flatMap(i=>i.kind==='group'?R.members(i.el).map(el=>({...R.rect(el),id:el.id,kind:el.dataset.kind,pin:i.pin})):[i]).filter(i=>!i.pin&&G.influence(i,p,radius)>.25&&!gesture.painted.has(i.id));const color=q('.clay-color').value;
    if(targets.length){B.write(targets.map(i=>({el:i.el,css:{[i.kind==='text'?'color':'background-color']:color,'background-image':'none'}})),'You painted this piece '+color+'.');targets.forEach(i=>gesture.painted.add(i.id));gesture.moved=true;}}
  function move(e){const at=point(e),b0=bounds();hoveringField=at.x>=0&&at.y>=0&&at.x<=b0.w&&at.y<=b0.h;if(hoveringField||gesture)lastPoint=at;if(!gesture){draw();return;}if(e.pointerId!==gesture.id)return;e.preventDefault();const d=gesture,p=lastPoint,dx=p.x-d.start.x,dy=p.y-d.start.y,b=bounds();
    if(!d.moved&&Math.hypot(dx,dy)<3&&tool!=='paint')return;d.moved=true;let next=d.now,label='',held=null;
    if(tool==='group'){d.path.push(p);d.groupIds=G.lasso(d.all,d.path);d.prev=p;say(d.groupIds.length+' pieces inside. Release to group them.');draw();return;}
    if(d.peel&&!d.peeled){if(Math.hypot(dx,dy)<56){say('Pull a little farther to peel this piece out.');draw();return;}R.peel(d.el);d.peeled=true;d.all=model();d.now=d.all;select(d.el);}
    if(d.resize){const i=d.all.find(i=>i.el===d.el),w=G.clamp(i.w+dx,i.minW,b.w-i.x),h=G.clamp(i.h+dy,i.minH,b.h-i.y);next=d.all.map(o=>o.id===i.id?{...o,w,h,font:G.clamp(i.font*w/i.w,i.minFont,120)}:{...o});held=i.id;label='You resized a piece by hand.';}
    else if(tool==='hand'||d.peel){const i=d.all.find(i=>i.el===d.el);let moved=G.contain({...i,x:i.x+dx,y:i.y+dy},b);d.guides=[];d.magnet=null;if(!e.shiftKey&&!d.peel){const snap=G.snap(moved,d.all.filter(o=>o.id!==i.id),b);moved=snap.item;d.guides=snap.guides;}if(magnets&&!e.shiftKey&&!d.peel){d.magnet=G.magnet(moved,d.all.filter(o=>o.id!==i.id),b);if(d.magnet)moved=d.magnet.item;}if(makeRoom&&!d.magnet){const pins=d.all.filter(o=>o.id!==i.id&&o.pin);if(pins.some(o=>G.overlaps(moved,o,0)))moved=G.nearestFree(moved,pins,b)||i;}next=d.all.map(o=>o.id===i.id?moved:{...o});held=d.magnet?[i.id,d.magnet.target]:i.id;label=d.peel?'You peeled out a piece and placed it freely.':'You placed a piece freely.';}
    else if(tool==='flow'){if(Math.hypot(p.x-d.path[d.path.length-1].x,p.y-d.path[d.path.length-1].y)>3)d.path.push(p);const group=d.all.filter(i=>d.flowIds.includes(i.id)),flow=G.flow(group,d.path,b);d.flowValid=!!flow;
      if(flow){const map=new Map(flow.map(i=>[i.id,i]));next=d.all.map(i=>map.get(i.id)||{...i});label='You drew a path for the cards to follow.';}else{say('Keep drawing a longer path for '+group.length+' cards.');d.prev=p;draw();return;}}
    else{const delta={x:p.x-d.prev.x,y:p.y-d.prev.y};const steps=Math.max(1,Math.ceil(Math.hypot(delta.x,delta.y)/Math.max(20,radius*.25)));next=d.now;
      for(let j=1;j<=steps;j++){const at={x:d.prev.x+delta.x*j/steps,y:d.prev.y+delta.y*j/steps};if(tool==='push')next=G.push(next,at,{x:delta.x/steps*.9,y:delta.y/steps*.9},radius,b);
        else if(tool==='grow')next=G.grow(next,at,-delta.y/steps*.006,radius,b);else if(tool==='smooth')next=G.smooth(next,at,radius,b);else if(tool==='paint')paint(at);}
      label={push:'You pushed the page with a brush.',grow:'You sculpted the size of nearby pieces.',smooth:'You smoothed the spacing and alignment.',paint:'You painted the page.'}[tool];}
    if(tool!=='paint'){const settled=settle(next,held);d.now=settled.items;d.lastOutcome=settled.unresolved;apply(d.now,label,d.resize||tool==='grow',d.all,d.seen);if(d.resize||tool==='grow')d.now.filter(i=>i.kind==='group'&&!i.pin).forEach(i=>{const state=d.groupSizes.get(i.id);if(state)R.resize(i.el,state,i.w,i.h);});
      // Text wrapping can change a rectangle after growing. Feed those actual dimensions back into collision resolution.
      if(d.resize||tool==='grow'){const measured=model();d.now=measured;const adjusted=settle(measured,held);d.now=adjusted.items;d.lastOutcome=adjusted.unresolved;apply(d.now,label,false,d.all,d.seen);}}
    d.label=label;d.prev=p;say(d.magnet?'Attach '+d.magnet.side+' on release. Hold Shift for free placement.':d.peel?'Released from the group. Keep dragging; Undo brings it back.':d.lastOutcome?'Some pieces touch. Move farther, use a smaller brush, or switch Make room off.':tool==='flow'?'The cards follow your line. Release to keep this arrangement.':tips[tool]);draw();
  }
  function finish(keep){if(!gesture)return;const d=gesture;gesture=null;try{field.releasePointerCapture(d.id);}catch(err){}
    if(keep&&d.peel&&!d.peeled){select(R.unit(d.el));say('Still attached. Pull farther to peel, or use Ungroup.');draw();return;}
    if(keep&&tool==='group'){const chosen=d.all.filter(i=>(d.groupIds||[]).includes(i.id)).map(i=>i.el);if(chosen.length>=2){const g=R.wrap(chosen);B.commit(d.before,'You looped '+chosen.length+' pieces into a sticky group.');select(g);setTool('hand');say('Stuck together. Grab any member, stretch the corner, or choose Peel a piece.');}else say('Include the centers of at least two unpinned pieces.');refresh();draw();return;}
    if(keep&&d.magnet&&d.moved){const target=items().find(e=>e.id===d.magnet.target);if(target){const g=R.wrap([target,d.el],'magnet');B.commit(d.before,'You attached a piece with magnetism.');select(g);say('Attached. Move them together, or use Peel a piece to pull one free.');refresh();draw();return;}}
    if(!keep||tool==='flow'&&!d.flowValid){B.restore(d.before);B.stopMotion();say(!keep?'Stroke cancelled. Everything is back where it was.':'That path was too short. Draw farther across the canvas.');}
    else if(d.moved){B.commit(d.before,d.label||'You painted the page.');say(d.lastOutcome?'Saved. Some pieces still touch; Undo is available.':'Shape kept. '+(tool==='hand'?'Double-click words to edit them.':'One stroke, one undo.'));}
    if(keep&&d.peeled){setTool('hand');say('Piece peeled free. Grab to move it; Undo reattaches it.');}
    refresh();draw();
  }
  function draw(){const ratio=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(innerWidth*ratio)||canvas.height!==Math.round(innerHeight*ratio)){canvas.width=Math.round(innerWidth*ratio);canvas.height=Math.round(innerHeight*ratio);canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';}ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,innerWidth,innerHeight);if(!active())return;const r=field.getBoundingClientRect();
    if(lastPoint&&(hoveringField||gesture)&&['push','grow','smooth','paint'].includes(tool)){ctx.beginPath();ctx.arc(r.left+lastPoint.x,r.top+lastPoint.y,radius,0,Math.PI*2);ctx.fillStyle='#16836509';ctx.fill();ctx.strokeStyle='#16836588';ctx.lineWidth=1.5;ctx.setLineDash([5,6]);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(r.left+lastPoint.x,r.top+lastPoint.y,3,0,Math.PI*2);ctx.fillStyle='#168365';ctx.fill();}
    if(selected&&R.isGroup(selected)){const b=selected.getBoundingClientRect();ctx.setLineDash([5,5]);ctx.strokeStyle='#168365';ctx.lineWidth=1.5;ctx.strokeRect(b.x-8,b.y-8,b.width+16,b.height+16);ctx.setLineDash([]);}
    if(gesture&&tool==='group'){const path=gesture.path,box=G.envelope(path.map(p=>({...p,w:0,h:0})));ctx.fillStyle='#16836514';ctx.strokeStyle='#168365';ctx.setLineDash([6,4]);ctx.fillRect(r.left+box.x,r.top+box.y,box.w,box.h);ctx.strokeRect(r.left+box.x,r.top+box.y,box.w,box.h);ctx.setLineDash([]);ctx.beginPath();path.forEach((p,i)=>ctx[i?'lineTo':'moveTo'](p.x+r.left,p.y+r.top));ctx.stroke();gesture.all.filter(i=>(gesture.groupIds||[]).includes(i.id)).forEach(i=>ctx.strokeRect(r.left+i.x-5,r.top+i.y-5,i.w+10,i.h+10));}
    if(gesture&&gesture.magnet){const target=gesture.now.find(i=>i.id===gesture.magnet.target);if(target){ctx.fillStyle='#e2b33a20';ctx.strokeStyle='#b18528';ctx.lineWidth=3;ctx.fillRect(r.left+target.x-6,r.top+target.y-6,target.w+12,target.h+12);ctx.strokeRect(r.left+target.x-6,r.top+target.y-6,target.w+12,target.h+12);}}
    if(gesture&&gesture.peel&&!gesture.peeled){ctx.strokeStyle='#b18528';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(r.left+gesture.start.x,r.top+gesture.start.y);ctx.lineTo(r.left+lastPoint.x,r.top+lastPoint.y);ctx.stroke();ctx.setLineDash([]);}
    if(gesture&&tool==='flow'){ctx.beginPath();gesture.path.forEach((p,i)=>ctx[i?'lineTo':'moveTo'](p.x+r.left,p.y+r.top));ctx.strokeStyle=gesture.flowValid?'#168365':'#b18528';ctx.lineWidth=3;ctx.lineCap='round';ctx.stroke();}
    if(gesture)gesture.guides.forEach(g=>{ctx.beginPath();ctx.setLineDash([4,4]);if(g.axis==='x'){ctx.moveTo(r.left+g.at,r.top);ctx.lineTo(r.left+g.at,r.bottom);}else{ctx.moveTo(r.left,r.top+g.at);ctx.lineTo(r.right,r.top+g.at);}ctx.strokeStyle='#6756d4aa';ctx.lineWidth=1;ctx.stroke();ctx.setLineDash([]);});}
  function textEditor(el){if(R.isGroup(el)){say('Double-click the words inside the group to edit them.');return;}if(!el){say('Grab a text piece first, or double-click its words.');return;}let target=el;if(el.dataset.kind==='card')target=el.querySelector('h2,p')||el;if(el.tagName==='IMG'){say('Image added. Its filename is used as alternative text.');return;}
    const editor=document.createElement('div');editor.className='clay-inline-editor';editor.innerHTML='<label>Edit these words<textarea aria-label="Edit selected text"></textarea></label><div class="row"><button data-cancel>Cancel</button><button data-save>Keep words</button></div>';shell.appendChild(editor);const input=editor.querySelector('textarea');input.value=target.innerText;input.focus();input.select();
    const close=()=>editor.remove();editor.querySelector('[data-cancel]').onclick=close;editor.querySelector('[data-save]').onclick=()=>{B.text(target,input.value);const unit=R.unit(target);if(R.isGroup(unit)){R.fit(unit);B.save();}close();refresh();say('Words saved. They remain real, selectable text in your exported page.');};input.onkeydown=e=>{e.stopPropagation();if(e.key==='Escape')close();if((e.ctrlKey||e.metaKey)&&e.key==='Enter')editor.querySelector('[data-save]').click();};}
  function add(kind,url,fileName){if(phone){say('Return to Desktop to add a piece.');return;}const before=B.begin(),el=document.createElement(kind==='card'?'article':kind==='button'?'a':kind==='image'?'img':'p');el.id='piece-'+Date.now().toString(36);el.dataset.sculptItem='';el.dataset.kind=kind;el.className='piece '+(kind==='card'?'note leaf':kind==='button'?'join':kind==='text'?'intro':'');
    if(kind==='card')el.innerHTML='<small>A new thought</small><h2>Something good.</h2><p>Double-click these words to make them yours.</p>';else if(kind==='button'){el.textContent='Explore the page';el.href='#story';}else if(kind==='image'){el.src=url;el.alt=fileName||'Added image';}else el.textContent='Start with a little thought.';
    field.appendChild(el);B.register(el,kind);const b=bounds(),p=lastPoint||{x:b.w*.55,y:240};B.write([{el,css:{position:'absolute',left:G.clamp(p.x/b.w*100,2,68)+'%',top:G.clamp(p.y,20,b.h-220)+'px',width:'27%',...(kind==='image'?{height:'190px'}:{})}},mobileRules(el)],'You added a '+kind+' to the page.');B.commit(before,'Added a '+kind+'.');q('.clay-more').hidden=true;q('[data-action=add]').setAttribute('aria-expanded','false');select(el);setTool('hand');say('Added. Grab it anywhere, or double-click its words.');}
  function imageOk(file){if(!file)return false;if(!/^image\/(png|jpeg|webp|gif|avif|svg\+xml)$/.test(file.type)){say('Choose a PNG, JPEG, WebP, GIF, AVIF or SVG image.');return false;}if(file.size>4*1024*1024){say('Choose an image smaller than 4 MB so it can save with your page.');return false;}return true;}
  // The one picture a piece shows: the piece itself, or the only picture inside a group.
  function imageOf(el){if(!el||!el.isConnected)return null;if(el.tagName==='IMG')return el;const imgs=el.querySelectorAll('img');return imgs.length===1?imgs[0]:null;}
  function replaceImage(img,file){if(!imageOk(file))return;B.picture(img,file,()=>{q('.clay-more').hidden=true;q('[data-action=add]').setAttribute('aria-expanded','false');select(R.unit(img));say('Picture replaced in the same place and size. Undo brings the old one back.');});}
  function readImage(file){if(!imageOk(file))return;const reader=new FileReader();reader.onload=()=>add('image',reader.result,file.name);reader.onerror=()=>say('That image could not be read. Try another file.');reader.readAsDataURL(file);}
  function showFormat(f){format=f;qa('[data-format]').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.format===f));b.setAttribute('aria-pressed',String(b.dataset.format===f));});q('.clay-dialog textarea').value=f==='html'?exportHTML:f==='css'?B.css():B.agent()+'\n\n# Sticky relationships\n'+R.describe().map(g=>g.id+' ('+g.bond+'): keep '+g.members.join(', ')+' together in this order on small screens.').join('\n');}
  function openExport(){if(gesture)finish(true);B.stopMotion();exportHTML=B.html();showFormat('html');q('.clay-export-state').replaceChildren();dialog.showModal();draw();}
  async function saveExport(){if(exportSaving)return;exportSaving=true;const state=q('.clay-export-state');state.textContent='Saving your standalone page…';q('[data-action=download]').disabled=true;
    try{if(location.protocol==='http:'||location.protocol==='https:'){const response=await fetch('/api/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({html:exportHTML})});if(!response.ok)throw new Error('No local export service');const result=await response.json();state.replaceChildren();const msg=document.createElement('span');msg.textContent='Saved. ';state.appendChild(msg);const preview=document.createElement('a');preview.textContent='Open exported page';preview.href=result.url;preview.target='_blank';preview.rel='noopener';state.appendChild(preview);const dl=document.createElement('a');dl.textContent='Download HTML';dl.href=result.url+'?download=1';dl.download='clay-page.html';state.appendChild(dl);}
      else throw new Error('File mode');
    }catch(err){if(exportURL)URL.revokeObjectURL(exportURL);exportURL=URL.createObjectURL(new Blob([exportHTML],{type:'text/html'}));state.replaceChildren();const dl=document.createElement('a');dl.textContent='Download HTML';dl.href=exportURL;dl.download='clay-page.html';state.appendChild(dl);const msg=document.createElement('span');msg.textContent=' — browser download; no local export server is running.';state.appendChild(msg);}
    finally{exportSaving=false;q('[data-action=download]').disabled=false;}}
  async function action(name){if(name==='undo'||name==='redo'){if(gesture)finish(false);B[name]();B.stopMotion();refresh();say(name==='undo'?'Undone.':'Redone.');return;}
    if(name==='magnets'){magnets=!magnets;q('[data-action=magnets]').setAttribute('aria-pressed',String(magnets));say(magnets?'Small text and buttons attach near cards and pictures. Hold Shift to bypass.':'Magnets off. Pieces remain independent.');}
    if(name==='ungroup'&&selected&&R.isGroup(selected)){const before=B.begin(),all=R.ungroup(selected);B.commit(before,'You released a sticky group.');select(all[0]);setTool('hand');say('Pieces released in place. Undo sticks them back together.');}
    if(name==='room'){makeRoom=!makeRoom;q('[data-action=room]').setAttribute('aria-pressed',String(makeRoom));say(makeRoom?'Neighbors will make room. Pinned pieces stay put.':'Overlap is allowed. Place pieces exactly where you want.');}
    if(name==='add'){const menu=q('.clay-more');menu.hidden=!menu.hidden;q('[data-action=add]').setAttribute('aria-expanded',String(!menu.hidden));}
    if(name==='space'){const before=B.begin();B.write([{el:field,css:{height:(field.clientHeight+300)+'px'}}],'You added more room to the canvas.');B.commit(before,'Added more canvas.');q('.clay-more').hidden=true;say('Another 300 pixels of room. Your exported page includes it.');refresh();}
    if(name==='edit')textEditor(selected);
    if(name==='replace'){const img=imageOf(selected);if(!img){say('Grab a picture first, then choose Replace image.');return;}fileFor=img;q('.clay-file').click();}
    if(name==='export')openExport();if(name==='close-export')dialog.close();if(name==='download')await saveExport();
    if(name==='copy'){try{await navigator.clipboard.writeText(q('.clay-dialog textarea').value);q('.clay-export-state').textContent='Copied '+(format==='agent'?'the change description':format.toUpperCase())+'.';}catch(err){q('.clay-dialog textarea').select();q('.clay-export-state').textContent='Select and copy the source with Ctrl+C.';}}
    if(name==='phone'){if(gesture)finish(false);phone=!phone;B.mobile(phone);B.stopMotion();q('[data-action=phone]').setAttribute('aria-pressed',String(phone));q('[data-action=phone]').textContent=phone?'Desktop':'Phone';qa('[data-tool],[data-action=room],[data-action=add]').forEach(b=>b.disabled=phone);say(phone?'Phone preview: your composition becomes a readable stack. Choose Desktop to sculpt.':tips[tool]);refresh();draw();}
    if(name==='preview'){live=!live;document.documentElement.toggleAttribute('data-sculpting',!live&&!original);q('[data-action=preview]').setAttribute('aria-pressed',String(live));q('[data-action=preview]').textContent=live?'Back to sculpt':'View site';q('.clay-bottom').classList.toggle('clay-hidden',live);refresh();draw();}
    if(name==='original'){if(gesture)finish(false);original=!original;phone=false;live=false;B.mobile(false);B.stopMotion();q('[data-action=phone]').textContent='Phone';q('[data-action=phone]').setAttribute('aria-pressed','false');q('[data-action=preview]').textContent='View site';q('[data-action=preview]').setAttribute('aria-pressed','false');qa('[data-action=phone],[data-action=preview]').forEach(b=>b.disabled=original);B.original(original);document.documentElement.toggleAttribute('data-sculpting',!original);q('[data-action=original]').textContent=original?'Back to sculpt':'Layout tools';q('.clay-bottom').classList.toggle('clay-hidden',original);refresh();draw();}
  }
  qa('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));qa('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));qa('[data-add]').forEach(b=>b.onclick=()=>b.dataset.add==='image'?(fileFor=null,q('.clay-file').click()):add(b.dataset.add));qa('[data-format]').forEach(b=>b.onclick=()=>showFormat(b.dataset.format));
  q('input[type=range]').oninput=e=>{radius=+e.target.value;q('output').textContent=radius;draw();};q('.clay-file').onchange=e=>{const f=e.target.files[0],img=fileFor;fileFor=null;e.target.value='';if(img&&img.isConnected)replaceImage(img,f);else readImage(f);};
  field.addEventListener('pointerdown',e=>start(e));handle.addEventListener('pointerdown',e=>start(e,true));window.addEventListener('pointermove',e=>{if(active())move(e);});window.addEventListener('pointerup',e=>{if(gesture&&e.pointerId===gesture.id)finish(true);});window.addEventListener('pointercancel',()=>finish(false));window.addEventListener('blur',()=>{if(gesture)finish(false);});
  field.addEventListener('dblclick',e=>{if(active()&&tool==='hand'){const hit=document.elementFromPoint(e.clientX,e.clientY),piece=hit&&hit.closest('[data-sculpt-item]');if(piece&&field.contains(piece)){e.preventDefault();let t=hit.closest('h1,h2,h3,p,a,button');textEditor(t&&piece.contains(t)?t:piece);}}});
  field.addEventListener('click',e=>{if(active()){e.preventDefault();e.stopPropagation();}});field.addEventListener('dragover',e=>{if(active()){e.preventDefault();e.dataTransfer.dropEffect='copy';}});field.addEventListener('drop',e=>{if(active()){e.preventDefault();lastPoint=point(e);const img=e.target.closest&&e.target.closest('img');if(img&&field.contains(img))replaceImage(img,e.dataTransfer.files[0]);else readImage(e.dataTransfer.files[0]);}});
  window.addEventListener('keydown',e=>{if(original||/^(INPUT|TEXTAREA|SELECT)$/.test(e.target.tagName)||e.target.isContentEditable)return;if(dialog.open)return;
    if(e.key==='Escape'){if(gesture){e.preventDefault();finish(false);}else{select(null);q('.clay-more').hidden=true;}return;}
    if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();action(e.shiftKey?'redo':'undo');return;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();action('redo');return;}
    if(!active()||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='Delete'&&selected){e.preventDefault();B.remove(selected);select(null);say('Removed. Undo brings it back.');return;}
    if(selected&&/^Arrow/.test(e.key)){e.preventDefault();const before=B.begin(),all=model(),start=all.map(o=>({...o})),i=all.find(i=>i.el===selected);if(i.pin){say('Unpin this piece before moving it.');return;}const n=e.shiftKey?10:2;i.x+=(e.key==='ArrowRight'?n:e.key==='ArrowLeft'?-n:0);i.y+=(e.key==='ArrowDown'?n:e.key==='ArrowUp'?-n:0);G.contain(i,bounds());const moved=settle(all,i.id,G.crowded(start)).items;apply(moved,'You nudged a piece with the keyboard.',false,start);B.commit(before,'Nudged a piece.');refresh();return;}
    const keys={b:'group',g:'hand',u:'push',s:'smooth',f:'flow',p:'paint',n:'pin',r:'grow'};if(keys[e.key.toLowerCase()])setTool(keys[e.key.toLowerCase()]);});
  window.addEventListener('resize',()=>{refresh();draw();});window.addEventListener('scroll',()=>{refresh();draw();},{passive:true});
  window.addEventListener('clay-save',e=>{q('.clay-status').textContent=e.detail.ok?'Saved in this browser. Export a page to keep a portable copy.':'Browser storage is full or unavailable. Export now to keep these changes.';if(!e.detail.ok)say('Could not autosave. Use Export to keep your page before closing.');});
  window.addEventListener('error',()=>{if(!seenError){seenError=true;say('Something interrupted the editor. Your last saved work stays here; reload to recover.');}});
  document.documentElement.setAttribute('data-sculpting','');setTool('hand');refresh();
})();
